### ISSUE TITLE
`String.prototype.endsWith` breaks Nashorn

### ISSUE THREAD

**Issue by AprilArcus** [zloirock/core-js#1128]
The `uncurryThis` helper introduced in https://github.com/zloirock/core-js/commit/fcbc2c878535b277f840997ab8ee819efd677888 is incompatible with Nashorn. When loading the [`endsWith` polyfill](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.string.ends-with.js), I receive this error:

`TypeError: [jdk.dynalink.beans.SimpleDynamicMethod boolean java.lang.String.endsWith(String)] is not a function`

Minimal repro in jRuby:

```
require 'java'
java_import 'javax.script.ScriptEngineManager'
engine = ScriptEngineManager.new.get_engine_by_name('nashorn')
bindings = engine.create_bindings
engine.eval("var uncurryThis = Function.prototype.call.bind(Function.prototype.call); var nativeEndsWith = uncurryThis(''.endsWith);", bindings)
```

Note that

```
> engine.eval("'foo'.endsWith('o')", bindings)
=> true
> engine.eval("''.endsWith", bindings)
=> #<Java::JdkDynalinkBeans::SimpleDynamicMethod:0x33f349ae>
> engine.eval("String.prototype.endsWith", bindings)
=> nil
```

Prior 3.19, a different error is produced:

`Java::JavaLang::AssertionError: unknown call type GET:METHOD|PROPERTY|ELEMENT:call(Object)Object@jdk.nashorn.internal.scripts.Script$Recompilation$6803$\^eval\_`

**Comment by zloirock** [comment]
It's a bug that should be fixed on the Nashorn side. Could you report them?

I can add a workaround, but too many libraries will not work in a similar case.

**Comment by AprilArcus** [comment]
Thanks for the quick fix. I have a patch of my own (https://github.com/zloirock/core-js/pull/1129) that you might be interested in, with a fuller explanation in the commit message. I've tested this in my JDK workflow.
